# Server Configuration
server:
  port: 8080

# Spring Configuration
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: "sa"
    password: "P@ssword123"
    url: "jdbc:h2:mem:test"
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: "/h2-console"
  application:
    name: "todolist"

app:
  allowed-origins:
    - 'http://localhost:4200'
    - 'http://localhost:3000'